name: "Test rolloff task"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: esquio-rolloff
        uses: ./
        with:
          esquioUrl: 'https://esquiodemoui.azurewebsites.net/'
          esquioApiKey: ${{ secrets.apikey }}
          flagId: 57
